ids:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm

names:
    - Perturbation-response genes
    - Gene Ontology (GSVA)
    - Reactome (GSVA)
    - Signaling Pathway Impact Analysis
    - Pathifier
    - PARADIGM

short:
    - PRGs
    - Gene Ontology
    - Reactome
    - SPIA
    - Pathifier
    - PARADIGM
