analysis_set:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - gsea_speed2016
    - gsva_gatza

ids:
    - speed_matrix
    - gsva_go
    - gsva_reactome
    - spia
    - pathifier
    - paradigm
    - mutation
    - gsva_speed1
    - gsea_speed2016
    - gsva_gatza

names:
    - Perturbation-response genes
    - Gene Ontology (GSVA)
    - Reactome (GSVA)
    - Signaling Pathway Impact Analysis
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED (Parikh et al. 2010)
    - SPEED (Iorio et al. 2016)
    - Gatza et al. (2009)

short:
    - PROGENy
    - Gene Ontology
    - Reactome
    - SPIA
    - Pathifier
    - PARADIGM
    - Mutations
    - SPEED (2010)
    - SPEED (2016)
    - Gatza (2009)
